[package]
name = "hyperstone"
version = "0.0.1"
authors = ["Fangdun Cai <cfddream@gmail.com>"]
edition = "2018"
description = "Hyperstone"
repository = "https://github.com/trek-rs/hyperstone"
documentation = "https://github.com/trek-rs/hyperstone/"
readme = "README.md"
keywords = ["hyperstone"]
license = "MIT/Apache-2.0"

[dependencies]
